### ISSUE TITLE
Wiki word vectors or English word vectors?

### ISSUE THREAD

**Issue by gvishal** [Babylonpartners/fastText_multilingual#13]
Fasttext provides multiple embeddings for English, trained on different sources: Wikipedia, Wikipedia + some corpus. Which ones were used to generate the translation matrices provided with this repository?

**Comment by nhammerla** [comment]
As mentioned in our README, all the embeddings used for alignment where taken from the fastText repo [here](https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md). AFAIK they were all trained on Wikipedia. However, as they do not provide any versioning info for those files it is difficult for us to know whether they have changed since.

**Comment by gvishal** [comment]
There was another set of embeddings provided by fasttext which were trained on other corpuses as well.
![image](https://user-images.githubusercontent.com/1708579/32553190-29609080-c4bc-11e7-8b15-a099fafbac51.png)
