### ISSUE TITLE
Similarity between English and other languages does not work

### ISSUE THREAD

**Issue by bocsiboti** [Babylonpartners/fastText_multilingual#16]
It seems that the similarity does not work between English and other languages. After applying the transformation into the English word space the similarity of the same word is not captured between English and other languages.

For example, I tried with the word 'monkey' in French 'singe', Russian 'обезьяна', and Hungarian 'majom'. In what follows, you can see that 'monkey' is not similar to any other words, whereas 'singe', 'обезьяна', and 'majom' are similar among each other.

(monkey, monkey) = 1.0000
(monkey, singe) = -0.0149
(monkey, обезьяна) = -0.0233
(monkey, majom) = 0.0332
(singe, monkey) = -0.0149
(singe, singe) = 1.0000
(singe, обезьяна) = 0.6160
(singe, majom) = 0.5465
(обезьяна, monkey) = -0.0233
(обезьяна, singe) = 0.6160
(обезьяна, обезьяна) = 1.0000
(обезьяна, majom) = 0.5460
(majom, monkey) = 0.0332
(majom, singe) = 0.5465
(majom, обезьяна) = 0.5460
(majom, majom) = 1.0000

Python code snippet:
```
path='/mnt/hdd/word2vec/'
supported_langs = ["en", "fr", "ru", "hu"]
weights = {}
for lang in supported_langs:
    lang_data = FastVector(vector_file=path + 'wiki.'+lang+'.vec')
    lang_data.apply_transform(path + 'alignment_matrices/'+lang+'.txt')
    weights[lang] = lang_data

words = [("monkey", "en"), ("singe", "fr"), ("обезьяна", "ru"), ("majom", "hu")]
words_weights = [weights[w[1]][w[0]] for w in words]
for i in range(0, len(words)):
    for y in range(0, len(words)):
        print("(%s, %s) = %.4f" % (words[i][0], words[y][0], FastVector.cosine_similarity(words_weights[i], words_weights[y])))

```

**Comment by nhammerla** [comment]
@bocsiboti Thanks for spotting this. It seems Facebook has updated some of the pre-trained word vectors since we last ran our alignment, rendering our alignment matrices pretty useless (alignment with English is affected by this, other pairs may still work).

We are in the process of re-running our alignments and will update the alignment matrices. Also we will include a list of MD5 hashes to compare your version of fasttext embeddings with the one used for alignment (since they are stored on S3 they are not versioned).

**Comment by nhammerla** [comment]
@bocsiboti We've updated the alignment matrices which should fix your issue. Thanks again for reporting this - it is hard for us to keep track of changes in the pre-trained embeddings as they are not versioned.
